@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Murillo Orico",
  "email": "murillo.orico@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "murillo.orico@gmail.com",
  "password": "123456"
}

###

# @name create_recipient
POST {{baseUrl}}/recipients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "recipient-2",
  "latitude": 91119,
  "longitude": 91199
}

###

# @name edit_recipient
PUT {{baseUrl}}/recipients/4e326b0e-b319-401f-add4-c23a49a71a54
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "recipient-1",
  "latitude": 10000.0,
  "longitude": 10000.0
}